# action.yml
---
name: 'MQL Compile'
description: 'Compiles MQL programs'
author: 'kenorb'
branding:
  icon: 'bar-chart'
  color: 'green'
inputs:
  Path:
    description: 'Path to compile'
    required: true
# outputs:
#  foo: # id of output
#    description: 'Foo'
runs:
  using: node12
  main: dist/index.js
  post: dist/index.js
