# action.yml
---
name: 'MQL Compile'
description: 'Compiles MQL programs'
author: 'kenorb'
branding:
  icon: 'bar-chart'
  color: 'green'
inputs:
  path:
    description: 'Path to compile'
    required: true
    default: '.'
  path-ignore:
    description: 'Path for compiler to ignore'
    required: false
    default: '**/*.mqh'
  github-token:
    description: 'secret token'
    required: true
  include:
    description: 'Path for includes'
    default: ''
  ignore-warnings:
    description: 'Whether to ignore compilation warnings'
    required: false
    default: false
  log-file:
    description: 'Specifies log filename for compilation messages.'
    required: false
    default: 'mql.log'
  mt-path:
    description: 'Platform path'
    required: false
    default: '.'
  syntax-only:
    description: 'Whether to check for syntax only (no binary file is generated)'
    required: false
    default: false
  init-platform:
    description: 'Initializes platform files (includes, example EAs, script examples)'
    required: false
    default: false
  verbose:
    description: 'Enables verbose mode (to print more messages)'
    required: false
    default: false
  working-directory:
    description: 'Working directory where to run commands'
    required: false
    default: '.'
runs:
  using: node18
  main: dist/index.js
  post: dist/index.js
