# action.yml
---
name: 'MQL Compile'
description: 'Compiles MQL programs'
author: 'kenorb'
branding:
  icon: 'bar-chart'
  color: 'green'
inputs:
  path:
    description: 'Path to compile'
    required: true
    default: '.'
  github-token:
    description: 'secret token'
    required: true
  include:
    description: 'Path for includes'
    default: '.'
  mt-version:
    description: 'MetaTrader platform version to use'
    required: false
    default: '5.0.0.2361'
  mt-cleanup:
    description: 'Whether to remove extracted metaeditor files after compilation'
    required: false
    default: false
  ignore-warnings:
    description: 'Whether to ignore compilation warnings'
    required: false
    default: false
  log-file:
    description: 'Specifies log filename for compilation messages.'
    required: false
    default: 'mql.log'
  syntax-only:
    description: 'Whether to check for syntax only (no binary file is generated)'
    required: false
    default: false
  verbose:
    description: 'Enables verbose mode (to print more messages)'
    required: false
    default: false
runs:
  using: node12
  main: dist/index.js
  post: dist/index.js
