---
name: Action@dev

on:
  - pull_request
  - push

jobs:
  Test-EA:
    runs-on: ubuntu-latest
    steps:
      - uses: ea31337/mql-action@dev
        with:
          OptTrace: true
          OptVerbose: true
          TestExpert: "MACD"
