---
name: Action

on:
  - pull_request
  - push

jobs:
  Local:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run local action
        uses: ./
        with:
          path: "."
          mt_version: '5.0.0.2361'
          mt_cleanup: true
          ignore_warnings: false
          log_file: 'mql-log-custom.log'
          verbose: true
          check_syntax_only: false
