---
name: Action

on:
  - pull_request
  - push

jobs:
  Local:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run local action (syntax only)
        uses: ./
        with:
          syntax-only: true
          verbose: true
      - name: Run local action (compile)
        uses: ./
        with:
          verbose: true
