---
name: Docker

on:
  - pull_request
  - push

jobs:
  Build-Dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Dockerfile
        run: docker build .
