---
name: Lint

on:
  pull_request:
    paths:
      - '**/*.md'
      - '**/*.y?ml'
  push:
    paths:
      - '**/*.md'
      - '**/*.y?ml'

jobs:
  Markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .
          config_file: ".markdownlint.yml"
  YAML:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: YAML check (yamllint)
        uses: ibiqlik/action-yamllint@master
        with:
          strict: true
