---
name: Test

on:
  pull_request:
    paths:
      - '**/*.md'
      - '**/*.y?ml'
  push:
    paths:
      - '**/*.md'
      - '**/*.y?ml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - run: npm run format-check
        if: false
      - run: npm run lint
        if: false
      - run: npm test
        if: false
